const fs = require('fs');

function fixFile(path) {
  let c = fs.readFileSync(path, 'utf8');
  c = c.replace(/famâÂ¡lia/g, 'família');
  c = c.replace(/famÃ­lia/g, 'família');
  c = c.replace(/imââveis/g, 'imóveis');
  c = c.replace(/Imââveis/g, 'Imóveis');
  c = c.replace(/imÃ³veis/g, 'imóveis');
  c = c.replace(/ImÃ³veis/g, 'Imóveis');
  c = c.replace(/confianâÂºa/g, 'confiança');
  c = c.replace(/confianÃ§a/g, 'confiança');
  c = c.replace(/regiâÃ£o/g, 'região');
  c = c.replace(/regiÃ£o/g, 'região');
  c = c.replace(/experiâÂªncia/g, 'experiência');
  c = c.replace(/experiÃªncia/g, 'experiência');
  c = c.replace(/seguranâÂºa/g, 'segurança');
  c = c.replace(/seguranÃ§a/g, 'segurança');
  c = c.replace(/ImobiliâÂ¡ria/g, 'Imobiliária');
  c = c.replace(/ImobiliÃ¡ria/g, 'Imobiliária');
  c = c.replace(/NegâÂ³cios/g, 'Negócios');
  c = c.replace(/NegÃ³cios/g, 'Negócios');
  c = c.replace(/JacarâÂ©/g, 'Jacaré');
  c = c.replace(/JacarÃ©/g, 'Jacaré');
  c = c.replace(/ChâÂ¡cara/g, 'Chácara');
  c = c.replace(/ChÃ¡cara/g, 'Chácara');
  c = c.replace(/SâÂ­tio/g, 'Sítio');
  c = c.replace(/SÃ­tio/g, 'Sítio');
  c = c.replace(/atuaâÂºÃ£o/g, 'atuação');
  c = c.replace(/atuaÃ§Ã£o/g, 'atuação');
  c = c.replace(/AtuaâÂºÃ£o/g, 'Atuação');
  c = c.replace(/AtuaÃ§Ã£o/g, 'Atuação');
  c = c.replace(/transparâÂªncia/g, 'transparência');
  c = c.replace(/transparÃªncia/g, 'transparência');
  c = c.replace(/negociaâÂºÃ£o/g, 'negociação');
  c = c.replace(/negociaÃ§Ã£o/g, 'negociação');
  c = c.replace(/mâÂ¡xima/g, 'máxima');
  c = c.replace(/mÃ¡xima/g, 'máxima');
  c = c.replace(/atenâÂºÃ£o/g, 'atenção');
  c = c.replace(/atenÃ§Ã£o/g, 'atenção');
  c = c.replace(/cartâÂ³rios/g, 'cartórios');
  c = c.replace(/cartÃ³rios/g, 'cartórios');
  c = c.replace(/jurâÂ­dica/g, 'jurídica');
  c = c.replace(/jurÃ­dica/g, 'jurídica');
  c = c.replace(/AvaliaâÂºÃ£o/g, 'Avaliação');
  c = c.replace(/AvaliaÃ§Ã£o/g, 'Avaliação');
  c = c.replace(/PortfâÂ³lio/g, 'Portfólio');
  c = c.replace(/PortfÃ³lio/g, 'Portfólio');
  c = c.replace(/disponâÂ­veis/g, 'disponíveis');
  c = c.replace(/disponÃ­veis/g, 'disponíveis');
  c = c.replace(/construâÂ­do/g, 'construído');
  c = c.replace(/construÃ­do/g, 'construído');
  c = c.replace(/InâÂ­cio/g, 'Início');
  c = c.replace(/InÃ­cio/g, 'Início');
  c = c.replace(/vocâÂ¬/g, 'você');
  c = c.replace(/vocÃª/g, 'você');
  c = c.replace(/âÂ¬/g, 'ê');
  c = c.replace(/âÂ¡/g, 'á');
  c = c.replace(/âÂ³/g, 'ó');
  c = c.replace(/âÂ­/g, 'í');
  c = c.replace(/âÂª/g, 'ê');
  c = c.replace(/âÂº/g, 'ç');
  c = c.replace(/ÂÆÃ¶Ã¬/g, '🔍');
  c = c.replace(/ÂÂ·/g, '·');
  c = c.replace(/Â·/g, '·');
  c = c.replace(/â€"/g, '—');
  c = c.replace(/Ã©/g, 'é');
  c = c.replace(/Ã£/g, 'ã');
  c = c.replace(/Ã§/g, 'ç');
  fs.writeFileSync(path, c, 'utf8');
  console.log('Corrigido: ' + path);
}

fixFile('app/page.tsx');
fixFile('app/admin/page.tsx');
